apiVersion: v1
kind: Service
metadata:
  name: pagamento-api-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: pagamento-api
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
