apiVersion: v1
kind: Secret
metadata:
  name: jwt-secrets
  namespace: default
type: Opaque
stringData:
  FIAP.CloudGames.Usuario.API: "FIAP_CloudGames_Usuario_Secret_Key_2024_Min_32_Chars_Long"
  FIAP.CloudGames.Jogo.API: "FIAP_CloudGames_Jogo_Secret_Key_2024_Min_32_Chars_Long"
  FIAP.CloudGames.Pagamento.API: "FIAP_CloudGames_Pagamento_Secret_Key_2024_Min_32_Chars_Long"
